#!/usr/bin/env python

from os.path import basename

from cli import *

_HELP = """Enqueue a task to process the new block.

Tasks are Celery tasks and the queue is RabbitMQ.

Configure bitcoind to use this task:

  # in /etc/bitcoind/bitcoind.conf
  blocknotify=/path/to/blocknotify %s

The BLOCK_HASH argument passed in by bitcoind will be serialized as
the first argument to the enqueued task."""

if __name__ == "__main__":
    run(basename(__file__), "BLOCK_HASH", "blocknotify", _HELP)
