#!/usr/bin/env python

from os.path import basename

from cli import *

_HELP = """Enqueue a task to process a wallet notification.

Tasks are Celery tasks and the queue is RabbitMQ.

Configure bitcoind to use this task:

  # in /etc/bitcoind/bitcoind.conf
  walletnotify=/path/to/blocknotify %s

The TXID argument passed in by bitcoind will be serialized as the
first argument to the enqueued task."""

if __name__ == "__main__":
    run(basename(__file__), "TXID", "walletnotify", _HELP)
